name: Update Profile Log

on:
  push:
    branches:
      - main

jobs:
  update-profile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install axios

      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          REPO_NAME: ${{ github.repository }}
        run: node .github/scripts/update-profile.js
